version: '3'
services:
  redis:
    container_name: adidas_redis
    image: "redis:6-alpine"
    ports:
      - "6379:6379"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../redis:/data
    restart: unless-stopped
    expose:
      - 6379
    environment:
      - 'API_PORT=6379'
  postgres:
    image: postgres:12-alpine
    container_name: adidas_postgres
    restart: unless-stopped
    ports:
      - "5557:5432"
    environment:
    - DEBUG=false
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=
    - POSTGRES_DB=adidas
    volumes:
      - ../db:/var/lib/postgresql
